.. _Flask: http://flask.pocoo.org/
.. _Flask Documentation: http://flask.pocoo.org/docs/latest/
.. _Flask Installation Documentation: http://flask.pocoo.org/docs/latest/installation
.. _Flask Quickstart Documentation: http://flask.pocoo.org/docs/latest/quickstart
.. _Jinja2: http://jinja.pocoo.org/
.. _Jinja2 Documentation: http://jinja.pocoo.org/docs
.. _Werkzeug: http://werkzeug.pocoo.org/
.. _Werkzeug Documentation: http://werkzeug.pocoo.org/docs
.. _Requests: http://python-requests.org
.. _Sphinx: http://www.sphinx-doc.org
.. _Nose: http://nose.readthedocs.io/
.. _Pylint: https://www.pylint.org/
